AWSTemplateFormatVersion: "2010-09-09"

Description: サンプルテンプレート

Parameters:
  VpcCidrBlock:
    Type: String
    Default: 10.0.0.0/16
  NameBase:
    Description: Name Tag Value
    Type: String
    Default: practice-cfn

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsSupport: true
      Tags: 
        - Key: Name
          Value: !Sub ${NameBase}-vpc

  # インターネットゲートウェイ
  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${NameBase}-igw

  # インターネットゲートウェイをVPCにアタッチ
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref IGW

  # パブリックサブネット
  PubSub1a:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref VPC
      CidrBlock: 10.0.10.0/24
      Tags:
        - Key: Name
          Value: !Sub ${NameBase}-pubsub-1a

  PubSub1c:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      VpcId: !Ref VPC
      CidrBlock: 10.0.11.0/24
      Tags:
        - Key: Name
          Value: !Sub ${NameBase}-pubsub-1c

  # プライベートサブネット
  PriSub1a:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref VPC
      CidrBlock: 10.0.20.0/24
      Tags:
        - Key: Name
          Value: !Sub ${NameBase}-prisub-1a

  PriSub1c:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      VpcId: !Ref VPC
      CidrBlock: 10.0.21.0/24
      Tags:
        - Key: Name
          Value: !Sub ${NameBase}-prisub-1c

  # ルートテーブル
  PubSubRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${NameBase}-pubsub-rt

  PriSubRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${NameBase}-prisub-rt

  # PubSubRTとインターネット間のルーティング
  PubSubToInternet:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PubSubRT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW

  # ルートテーブルをサブネットに関連付け
  AssoPubSubRT1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PubSub1a
      RouteTableId: !Ref PubSubRT

  AssoPubSubRT1c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PubSub1c
      RouteTableId: !Ref PubSubRT

  AssoPriSubRT1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PriSub1a
      RouteTableId: !Ref PriSubRT

  AssoPriSubRT1c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PriSub1c
      RouteTableId: !Ref PriSubRT

  #ElasticIP作成
  ElasticIPAssociate:
    Type: AWS::EC2::EIPAssociation
    DependsOn: EC2Instance
    Properties: 
      EIP: 35.76.45.95
      InstanceId: !Ref EC2Instance

  # EC2インスタンス
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-northeast-1a
      KeyName: circleci-demo
      ImageId: ami-08e5331432710bf80
      InstanceType: t2.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref PubSub1a
          GroupSet:
            - !Ref EC2SG
      UserData: !Base64 |
        #!/bin/bash
        sudo yum install -y git
      Tags:
        - Key: Name
          Value: !Sub ${NameBase}-ec2

  # セキュリティグループ
  EC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${NameBase}-ec2-sg
      GroupDescription: Allow SSH and HTTP access only IP address
      VpcId: !Ref VPC
      SecurityGroupIngress:
        # http
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        # ssh
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        # puma
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${NameBase}-ec2-sg

  # RDS
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "16"
      DBInstanceClass: db.t2.micro
      AvailabilityZone: ap-northeast-1a
      BackupRetentionPeriod: "7"
      DBInstanceIdentifier: !Sub ${NameBase}-rds
      DBName: circleci2demo
      DBParameterGroupName: !Ref DBParameterGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: mysql
      EngineVersion: "8.0"
      MasterUsername: "root"
      MasterUserPassword: "dbpassword"
      MultiAZ: "false"
      PreferredBackupWindow: "18:00-18:30"
      PreferredMaintenanceWindow: "sat:19:00-sat:19:30"
      PubliclyAccessible: "false"
      StorageType: gp2
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${NameBase}-rds
    DeletionPolicy: "Delete"

  # パラメータグループ
  DBParameterGroup:
    Type: "AWS::RDS::DBParameterGroup"
    Properties:
      Family: "MySQL8.0"
      Description: !Sub "${NameBase}-mysql80"

  # セキュリティグループ
  RDSSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      VpcId: !Ref VPC
      GroupName: !Sub "${NameBase}-rds-sg"
      GroupDescription: !Sub "${NameBase}-rds-sg"
      Tags:
        - Key: "Name"
          Value: !Sub "${NameBase}-rds-sg"
      SecurityGroupIngress:
        # MySQL/Aurora
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref EC2SG

  # サブネットグループ
  DBSubnetGroup: 
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupName: !Sub "${NameBase}-dbsub-gp"
      DBSubnetGroupDescription: !Sub "${NameBase}-dbsub-gp"
      SubnetIds: 
        - !Ref PriSub1a
        - !Ref PriSub1c