---

- name: yum install packages
  yum:
    state: latest
    lock_timeout: 180
    name:
      - git
      - gcc
      - gcc-c++
      - openssl-devel
      - libyaml-devel
      - readline-devel
      - zlib-devel
      - libffi-devel

- name: install rbenv
  git:
      repo: https://github.com/sstephenson/rbenv.git
      dest: /usr/local/rbenv

- name: generate rbenv .sh file
  template:
      src: rbenv_system.sh.j2
      dest: /etc/profile.d/rbenv.sh
      owner: root
      group: root
      mode: 0755

- name: install ruby-build
  git:
      repo: https://github.com/sstephenson/ruby-build.git
      dest: /usr/local/rbenv/plugins/ruby-build

- name: generate group for deploy
  group:
      name: deploy
      
- name: add ansible user to deploy group
  user:
      name: ansible
      groups: deploy

- name: change ownership group of rbenv to deploy group
  file:
      path: /usr/local/rbenv
      owner: root
      group: deploy
      recurse: yes
      state: directory

- name: install rbenv
  shell: bash -lc "rbenv install --skip-existing 2.6.3"

- name: set installed ruby version to global
  shell: bash -lc "rbenv global 2.6.3"

- name: install bundler
  gem:
      name: bundler
      user_install: no
      executable: /usr/local/rbenv/shims/gem